CRMsoftware/CRMsoftware/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from organs import views as organs_view
from users import views as users_view
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views

router = DefaultRouter()
router.register('organs', organs_view.OrgansListApi)
router.register('users', users_view.UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('organs/', include('organs.urls')),
    # path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('quotes/', include('quotes.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
]


# urlpatterns += [
#     path('api-token-auth/', views.obtain_auth_token)
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CRMsoftware/quotes/urls.py
from django.urls import path
from . import views


app_name = 'quotes'

urlpatterns = [
    path('new_quote/', views.CreateQuotes.as_view(), name='new_quote'),
    path('quote_list/', views.QuoteList.as_view(), name='quote_list'),
    path('quote_detail/<int:pk>', views.QuoteDetail.as_view(), name='quote_detail'),
    path('quote_pdf/<int:pk>', views.QuotePDF.as_view(), name='quote_pdf'),
    path('send_email/<int:pk>', views.send_email_to_organs, name='send-email'),
]

CRMsoftware/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('profile/edit/', views.EditUserProfile.as_view(), name='edit-profile'),
    path('must/', views.must, name='must')
]

CRMsoftware/quotes/models.py
from decimal import Decimal

from django.db import models
from django_jalali.db import models as jmodels
from django.contrib.auth import get_user_model
from django.db.models import Sum, F, Max, FloatField, ExpressionWrapper


class Quote(models.Model):
    """
    Create new Quote to use in next level
    """
    organ = models.ForeignKey('organs.Organization', on_delete=models.PROTECT)
    created_at = jmodels.jDateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)

    def __str__(self):
        return f' فاکتور شماره {self.pk} برای {self.organ}'

    def get_formatted_date(self):
        return self.created_at.strftime(format=('%Y-%m-%d'))

    def get_price_without_discount(self):
        return self.quoteitem_set.all().annotate(price_without_discount=F('qty') * F('product__price')) \
            .aggregate(Sum('price_without_discount'))['price_without_discount__sum']

    def get_price_with_discount(self):
        price_without_discount = self.quoteitem_set.all().annotate(price_without_discount=F('qty') * F('product__price')) \
            .aggregate(Sum('price_without_discount'))['price_without_discount__sum']
        price_with_discount = self.quoteitem_set.all().annotate(price_with_discount=ExpressionWrapper \
            (price_without_discount - (F('discount') / Decimal('100.0') * price_without_discount), output_field=FloatField()))
        return price_with_discount.aggregate(Max('price_with_discount'))['price_with_discount__max']

    def get_price_with_tax(self):
        price_without_discount = self.quoteitem_set.all().annotate(price_without_discount=F('qty') * F('product__price')) \
            .aggregate(Sum('price_without_discount'))['price_without_discount__sum']
        price_with_discount = self.quoteitem_set.all().annotate(price_with_discount=ExpressionWrapper(
            price_without_discount - (F('discount') / Decimal('100.0') * price_without_discount),
            output_field=FloatField())).aggregate(Max('price_with_discount'))['price_with_discount__max']
        price_with_tax = self.quoteitem_set.all().annotate(price_with_tax=ExpressionWrapper(price_with_discount + \
                                    (F('tax') / Decimal('100') * price_with_discount), output_field=FloatField()))
        return price_with_tax.aggregate(Max('price_with_tax'))['price_with_tax__max']


class QuoteItem(models.Model):
    """
    Choice quote and adding products to it
    """
    quote = models.ForeignKey(Quote, on_delete=models.PROTECT)
    product = models.ForeignKey('products.Product', on_delete=models.PROTECT)
    qty = models.PositiveIntegerField(default=1)
    discount = models.FloatField(default=0)
    tax = models.FloatField(default=5)

    def __str__(self):
        return f'{self.quote}'


class Email(models.Model):
    """
    save history of quotes mail
    """
    created_at = jmodels.jDateTimeField(auto_now_add=True,)
    email_sender = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='user_sender')
    email_receiver = models.EmailField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.email_sender}'

    def get_formatted_date(self):
        return self.created_at.strftime('%Y-%m-%d')

CRMsoftware/quotes/forms.py
from .models import QuoteItem
from django.forms import modelformset_factory


QuoteItemFormSet = modelformset_factory(QuoteItem, fields=('product', 'qty', 'discount'), extra=1)

CRMsoftware/quotes/views.py
import weasyprint
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from . import models, tasks, forms
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.core import mail
from django.utils.html import strip_tags
from .models import Email
from rest_framework.exceptions import NotAuthenticated
from django.http import JsonResponse, HttpResponse
from django.utils.decorators import method_decorator
from organs.models import Organization # noqa
from django.urls import reverse_lazy


@method_decorator(csrf_exempt, name='dispatch')
class CreateQuotes(LoginRequiredMixin, CreateView):
    """
        create quotes for organs, using formset
    """
    template_name = 'quotes/new_quote.html'

    def get_context_data(self, **kwargs):
        formset = forms.QuoteItemFormSet(queryset=models.QuoteItem.objects.none())
        organizations = Organization.objects.filter(created_by=self.request.user)
        return {
            'formset': formset,
            'organizations': organizations,
        }

    def post(self, *args, **kwargs):
        formset = forms.QuoteItemFormSet(data=self.request.POST)
        if formset.is_valid() and self.request.POST['organization']:
            try:
                organization = Organization.objects.get(pk=self.request.POST['organization'], created_by=self.request.user)
                quote = models.Quote.objects.create(created_by=self.request.user, organ=organization)

                for form in formset:
                    form.instance.quote = quote
                    form.save()
                messages.success(self.request, 'فاکتور با موفقیت صادر شد')
                return redirect('quotes:quote_list')
            except:
                messages.error(self.request, 'لطفا اطلاعات درست را وارد نمایید')
                return redirect('quotes:quote_list')
        else:
            messages.error(self.request, 'لطفا اطلاعات درست را وارد نمایید')
            return redirect('quotes:quote_list')


class QuoteList(LoginRequiredMixin, ListView):
    """
    Show the list of quotes
    """
    model = models.Quote
    template_name = 'quotes/quote_item_form.html'
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_anonymous:
            raise NotAuthenticated('You need to be logged on.')
        return models.Quote.objects.filter(created_by=self.request.user)


class QuoteDetail(LoginRequiredMixin, DetailView):
    """
    Show the detail of single quote
    """
    model = models.Quote
    template_name = 'quotes/quote_detail.html'
    extra_context = {'quote_pk': models.QuoteItem.quote}

    def get_queryset(self):
        return models.Quote.objects.filter(created_by=self.request.user)


class QuotePDF(LoginRequiredMixin, DetailView):
    """
    Rendering quote to PDF
    """
    template_name = 'quotes/quote_pdf.html'
    model = models.Quote

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        content = response.rendered_content
        pdf = weasyprint.HTML(string=content, base_url='http://127.0.0.1:8000').write_pdf()
        pdf_response = HttpResponse(content=pdf, content_type='application/pdf')
        return pdf_response

    def get_queryset(self):
        return models.Quote.objects.filter(created_by=self.request.user)


@require_http_methods(["GET"])
@login_required
def send_email_to_organs(request, pk):
    """
    preparing data and send them to celery task
    """
    try:

        html_message = render_to_string('quotes/quote_pdf.html', context={'object': models.Quote.objects.get(pk=pk, created_by=request.user)})
        plain_message = strip_tags(html_message)
        to = models.Quote.objects.get(pk=pk).organ.email
        email_sender1 = request.user.username
        # mail.send_mail(subject, plain_message, from_email, [to], html_message=html_message)
        tasks.send_email.delay(plain_message, email_sender1, [to], html_message=html_message)
        messages.success(request, 'ایمیل با موفقیت ارسال شد')
        return redirect('quotes:quote_list')

    except:

        messages.error(request, 'ایمیل ارسال نشد')
        return redirect('quotes:quote_list')

CRMsoftware/quotes/templates/quotes/factor.html
                                                    {{ object }}

<P>نام محصولات</P>                <P>تعداد</P>           <P>قیمت هر عدد دستگاه</P>            <P>درصد تخفیف</P>              <P>درصد مالیات</P>

{% for object in object.quoteitem_set.all %}
{{ object.tax }}                        {{ object.discount }}                         {{ object.product.price }}                            {{ object.qty }}                       {{ object.product }}
                        {% endfor %}




<p>مجموع خرید بدون تخفیف :</p>  {{ object.get_price_without_discount }}
<p>مجموع خرید با تخفیف :</p>    {{ object.get_price_with_discount }}
<p>مجموع نهایی خرید با احتساب مالیات :</p>  {{ object.get_price_with_tax }}

CRMsoftware/quotes/templates/quotes/new_quote.html
{% extends 'organs/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <form class="mt-4 mb-3" method="post" enctype="multipart/form-data">{% csrf_token %}

        <div class="container">
            <div class="jumbotron">
                <h1 class="text font-weight-bold">ایجاد پیش فاکتور</h1>
                <button>
                    <a href="{% url 'quotes:quote_list' %}">بازگشت</a>
                </button>
                <div class="form-group col-lg-3">
                    <label for="organization" class="text-info">انتخاب سازمان</label>
                    <select class="form-control" id="organization" name="organization" required>
                        <option value="0">None</option>
                        {% for organization in organizations %}
                            <option value="{{ organization.pk }}">{{ organization.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="container">
                <div class="col-12">

                        {{ formset.management_form }}

                        {% for form in formset %}
                            <div class='table table-dark table-bordered'>
                                <table class='no_error'>
                                    <thead>
                                    <tr>
                                        <th>محصولات</th>
                                        <th>تعداد</th>
                                        <th>درصد تخفیف</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td aria-required="true">{{ form.product }}</td>
                                        <td>{{ form.qty }}</td>
                                        <td>{{ form.discount }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        {% endfor %}
                        <button class="btn btn-info" type="submit" style="">صدور فاکتور</button>

                        <input type="button" class="btn btn-info" value="ردیف جدید" id="add_more">

                </div>
            </div>
        </div>
    </form>
{% endblock %}


{% block page_scripts %}
    <script>
        $(document).ready(function () {
            $('#add_more').click(function () {
                cloneMore('div.table:last', 'form');
            });

            function cloneMore(selector, type) {
                var newElement = $(selector).clone(true);
                var total = $('#id_' + type + '-TOTAL_FORMS').val();
                newElement.find(':input').each(function () {
                    var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
                    var id = 'id_' + name;
                    $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
                });
                newElement.find('label').each(function () {
                    var newFor = $(this).attr('for').replace('-' + (total - 1) + '-', '-' + total + '-');
                    $(this).attr('for', newFor);
                });
                total++;
                $('#id_' + type + '-TOTAL_FORMS').val(total);
                $(selector).after(newElement);
            }

        });
    </script>

{% endblock %}

CRMsoftware/quotes/templates/quotes/quote_detail.html
{% extends 'organs/base.html' %}
{#{% load humanize %}#}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Quote Detail{% endif %}
{% endblock %}
{% block content %}

    <form method="get">
        <div class="container">
            <div class="jumbotron">
                <h1>{{ object }}</h1>
                <button>
                    <a href="{% url 'quotes:quote_list' %}">بازگشت</a>
                </button>
                <button>
                    <a href="{% url 'quotes:quote_pdf' object.pk %}">PDF</a>
                </button>
            </div>


            <div class="container">
                <div class="col-sm">

                    <table class="table table-striped" style="background-color: white">
                        <thead>
                        <tr>
                            <th scope="col">نام محصولات</th>
                            <th scope="col">تعداد</th>
                            <th scope="col">قیمت هر عدد دستگاه</th>
                            <th scope="col">درصد تخفیف</th>
                            <th scope="col">درصد مالیات</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object.quoteitem_set.all %}
                            <tr>
                            <td>{{ object.product }}<br></td>
                            <td>{{ object.qty }}</td>
                            <td>$ {{ object.product.price }}</td>
                            <td>{{ object.discount }}</td>
                            <td>{{ object.tax }}</td>
                        {% endfor %}
                        </tr>

                        </tbody>
                    </table>
                    <table class="table table-striped" style="background-color: white">
                        <thead>
                        <tr>
                            <th scope="col">مجموع خرید بدون تخفیف</th>
                            <th scope="col">مجموع خرید با تخفیف</th>
                            <th scope="col">مجموع نهایی خرید با احتساب مالیات</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                            <td>$ {{ object.get_price_without_discount }}<br></td>
                            <td>$ {{ object.get_price_with_discount }}</td>
                            <td>$ {{ object.get_price_with_tax }}</td>
                        </tr>

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </form>

{% endblock %}

CRMsoftware/quotes/templates/quotes/quote_item_form.html
{% extends 'organs/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% block title %}
    Quotes
{% endblock %}
{% block content %}
    <div class="container-fluid col-lg-10">

        <div class="button btn-sm">
            <button class="header btn-block"><a style="color: black" href="{% url 'quotes:new_quote' %}">ایجاد پیش
                فاکتور</a>
            </button>
        </div>
        <form method="get">

            <div class="product-list">
                <table class="table table-striped" style="background-color: white">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">نام سازمان</th>
                        <th scope="col">ثبت توسط</th>
                        <th scope="col">تاریخ ایجاد</th>
                        <th scope="col">PDF خروجی</th>
                        <th scope="col">ارسال به ایمیل مخاطب</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for organ in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a href="{% url 'quotes:quote_detail' organ.pk %}">{{ organ.quoteitem_set.first }}</a>
                            </td>
                            <td>{{ organ.created_by }}</td>
                            <td>{{ organ.created_at|date:"Y-m-d , H:i:s" }}</td>
                            <td><a href="{% url 'quotes:quote_pdf' organ.pk %}">دریافت</a></td>
                            <td><a href="{% url 'quotes:send-email' organ.pk %}">ارسال</a></td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </form>


        {% include 'organs/pagination.html' %}

    </div>

{% endblock %}

CRMsoftware/quotes/templates/quotes/quote_pdf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Quote PDF</title>
    <style>
        h1 {
            text-align: center;
        }

        table {
            border: 1px solid;
            margin: 0 auto;
            width: 70%;
        }

        td, th {
            text-align: center;
            border: 1px solid;
        }

    </style>

</head>
<body>

<form method="get">
    <div class="container">
        <div class="jumbotron">
            <h1>{{ object }}</h1>
        </div>


        <div class="container">
            <div class="col-sm">

                <table class="table table-striped" style="background-color: white">
                    <thead class="glyphicon">
                    <tr>
                        <th scope="col">نام محصولات</th>
                        <th scope="col">تعداد</th>
                        <th scope="col">قیمت هر عدد دستگاه</th>
                        <th scope="col">درصد تخفیف</th>
                        <th scope="col">درصد مالیات</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object.quoteitem_set.all %}
                        <tr>
                        <td>{{ object.product }}<br></td>
                        <td>{{ object.qty }}</td>
                        <td>$ {{ object.product.price }}</td>
                        <td>{{ object.discount }}</td>
                        <td>{{ object.tax }}</td>
                    {% endfor %}
                    </tr>

                    </tbody>
                </table>
                <table class="table table-striped" style="background-color: white">
                    <thead>
                    <tr>
                        <th scope="col">مجموع خرید بدون تخفیف</th>
                        <th scope="col">مجموع خرید با تخفیف</th>
                        <th scope="col">مجموع نهایی خرید با احتساب مالیات</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>$ {{ object.get_price_without_discount }}<br></td>
                        <td>$ {{ object.get_price_with_discount }}</td>
                        <td>$ {{ object.get_price_with_tax }}</td>
                    </tr>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</form>
</body>
</html>