CRMsoftware/CRMsoftware/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from organs import views as organs_view
from users import views as users_view
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views

router = DefaultRouter()
router.register('organs', organs_view.OrgansListApi)
router.register('users', users_view.UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('organs/', include('organs.urls')),
    # path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('quotes/', include('quotes.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
]


# urlpatterns += [
#     path('api-token-auth/', views.obtain_auth_token)
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CRMsoftware/organs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create_organ/', views.CreateNewOrganization.as_view(), name='create_organ'),
    # path('organ_product/', views.ShowAddEntryForm.as_view(), name='organ_product'),
    path('organ_list/', views.OrgansList.as_view(), name='organ_list'),
    path('organ_detail/<int:pk>', views.OrgansDetail.as_view(), name='organ_detail'),
    path('organ_edit/<int:pk>', views.EditOrgan.as_view(), name='organ_edit'),
    path('organ_product/', views.OrganizationNewProduct.as_view(), name='organ_product'),
    path('followup/create/<int:pk>', views.CreateFollowUp.as_view(), name='organ-description'),
    path('followup/detail/<int:pk>', views.FollowUpDetail.as_view(), name='followup-detail')
]

CRMsoftware/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    # path('<slug:category_slug>/', views.CategoryList.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.ProductDetail.as_view(), name='product_detail'),
    ]

CRMsoftware/quotes/urls.py
from django.urls import path
from . import views


app_name = 'quotes'

urlpatterns = [
    path('new_quote/', views.CreateQuotes.as_view(), name='new_quote'),
    path('quote_list/', views.QuoteList.as_view(), name='quote_list'),
    path('quote_detail/<int:pk>', views.QuoteDetail.as_view(), name='quote_detail'),
    path('quote_pdf/<int:pk>', views.QuotePDF.as_view(), name='quote_pdf'),
    path('send_email/<int:pk>', views.send_email_to_organs, name='send-email'),
]

CRMsoftware/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('profile/edit/', views.EditUserProfile.as_view(), name='edit-profile'),
    path('must/', views.must, name='must')
]

CRMsoftware/organs/models.py
from django.core.validators import RegexValidator
from django.db import models
from django_jalali.db import models as jmodels
from products.models import Product # noqa
from django.contrib.auth import get_user_model


phone_regex = RegexValidator(regex='^0[0-9]{2,}[0-9]{7,}$', message='phone number invalid')


class OrganizationProduct(models.Model):
    """
    Products of organs
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Organization(models.Model):
    """
    Model to save the specifications of organs
    """
    province = models.CharField(max_length=100)
    name = models.CharField(max_length=150)
    organization_phone = models.CharField(validators=[phone_regex], max_length=11)
    employees_number = models.PositiveIntegerField(default=1)
    owner = models.CharField(max_length=150)
    email = models.EmailField()
    owner_phone = models.CharField(validators=[phone_regex], max_length=11)
    organization_product = models.ManyToManyField('OrganizationProduct')
    created_at = jmodels.jDateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'created_by'], name='UniqueOrgan')
        ]

    def __str__(self):
        return self.name

    # def get_related_product(self):
    #     related = OrganizationProduct.objects.all()
    #     return Product.objects.filter(follow_product__in=related).distinct()


class FollowUp(models.Model):
    """
    model to save organ's followup
    """
    description = models.TextField(blank=True)
    organ = models.ForeignKey(Organization, on_delete=models.CASCADE)
    created = jmodels.jDateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.organ}'

CRMsoftware/organs/forms.py
from django import forms
from . import models


# class EntryOrganizationForm(forms.ModelForm):
#     class Meta:
#         model = models.Organization
#         fields = [
#             'province',
#             'name',
#             'organization_phone',
#             'employees_number',
#             'owner',
#             'email',
#             'owner_phone',
#             'organization_product',
#         ]


class FollowUpForm(forms.ModelForm):
    class Meta:
        model = models.FollowUp
        fields = [
            'description'
        ]

CRMsoftware/organs/views.py
import logging
from django.shortcuts import redirect
from django.http import JsonResponse, HttpResponse
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import CreateView, UpdateView
from . import models, serializers, forms
from products.models import Product  # noqa
from rest_framework import generics, filters, viewsets, permissions
from rest_framework.exceptions import NotAuthenticated
from rest_framework.pagination import PageNumberPagination
from rest_framework.authtoken.models import Token

logger = logging.getLogger(__name__)  # logger object


@method_decorator(csrf_exempt, name='dispatch')
class CreateNewOrganization(LoginRequiredMixin, CreateView):
    """
    view for create new organization
    """
    queryset = models.Organization.objects.all()
    fields = [
        'province',
        'name',
        'organization_phone',
        'employees_number',
        'owner',
        'email',
        'owner_phone',
        'organization_product',
    ]
    template_name = 'organs/add_entry.html'
    extra_context = {'organization_products': models.OrganizationProduct.objects.all()}

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid input.')
        return reverse_lazy('create_organ')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        try:
            messages.success(self.request, 'سازمان جدید به لیست سازمانها اضافه شد')
            return super().form_valid(form)
        except:
            messages.error(self.request, 'Invalid input.')
            return redirect(reverse_lazy('create_organ'))

    def get_success_url(self):
        return reverse('organ_list')


@method_decorator(csrf_exempt, name='dispatch')
class EditOrgan(LoginRequiredMixin, UpdateView):
    """
        view for edit organs
    """
    model = models.Organization
    fields = (
        'organization_phone',
        'employees_number',
        'owner',
        'email',
        'owner_phone',
    )
    template_name = 'organs/organization_form.html'

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid input.')
        return reverse_lazy('create_organ')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        try:
            messages.success(self.request, 'مشخصات سازمان با موفقیت ویرایش شد')
            return super().form_valid(form)
        except:
            messages.error(self.request, 'Invalid input.')
            return redirect(reverse_lazy('create_organ'))

    def get_queryset(self):
        return models.Organization.objects.filter(created_by=self.request.user)

    def get_success_url(self):
        return reverse('organ_list')


class OrgansList(LoginRequiredMixin, ListView):
    """
    Show the list of organs
    """
    model = models.Organization
    template_name = 'organs/organization_list.html'
    paginate_by = 5

    def get_queryset(self):
        return models.Organization.objects.filter(created_by=self.request.user)


@method_decorator(csrf_exempt, name='dispatch')
class OrgansDetail(LoginRequiredMixin, DetailView):
    """
    Show the detail of organs
    """
    model = models.Organization

    def get_related_products(self):
        organ = self.get_object()
        organ_products = organ.organization_product.all()
        related = Product.objects.filter(follow_product__in=organ_products).distinct()
        return related

    def get_context_data(self, **kwargs):
        c = super().get_context_data()
        c['offer_product'] = self.get_related_products()
        return c

    def get_queryset(self):
        return models.Organization.objects.filter(created_by=self.request.user)


class OrganizationNewProduct(LoginRequiredMixin, CreateView):
    """
    Create new organs product
    """
    model = models.OrganizationProduct
    fields = [
        'name'
    ]
    success_url = reverse_lazy('create_organ')


@method_decorator(csrf_exempt, name='dispatch')
class CreateFollowUp(LoginRequiredMixin, CreateView):
    """
    Create new followUp for organs
    """
    model = models.FollowUp
    fields = [
        'description'
    ]
    template_name = 'organs/followup_form.html'

    def form_invalid(self, form):
        return JsonResponse(data={
            'success': 'False',
        }, status=400)

    def form_valid(self, form):
        form.save(commit=False).created_by = self.request.user
        form.save(commit=False).organ = models.Organization.objects.get(pk=self.kwargs['pk'])
        form.save()
        return JsonResponse(data={
            'success': 'True',
        }, status=200)

    def get_context_data(self, **kwargs):
        context = {
            'organ_obj': models.Organization.objects.get(pk=self.kwargs['pk']),
        }
        return context


class FollowUpDetail(LoginRequiredMixin, DetailView):
    queryset = models.FollowUp.objects.all()
    template_name = 'organs/followup_detail.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        context = super(FollowUpDetail, self).get_context_data(**kwargs)
        context['description'] = models.FollowUp.objects.filter(organ_id=pk)
        return context

    def get_queryset(self):
        return models.Organization.objects.filter(created_by=self.request.user)


"""
DRF
"""


class OrgansListApi(viewsets.ModelViewSet):
    """
    this view can represent api for organizations data
    """
    queryset = models.Organization.objects.all()
    serializer_class = serializers.OrgansSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['name']
    pagination_class = PageNumberPagination
    permission_classes = [permissions.IsAuthenticated]

    # token = Token.objects.create(user=models.Organization.created_by)
    # print(token.key)

    def get_queryset(self):
        return models.Organization.objects.filter(created_by_id=self.request.user.pk)

CRMsoftware/organs/templates/organs/add_entry.html
{% extends 'organs/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% block content %}

    <div class="container col-4" style="color: white">
        <form method="post">{% csrf_token %}
            <div class="form-group">استان
                {{ form.province|add_class:'form-control' }}
            </div>
            <div class="form-group">نام شرکت
                {{ form.name|add_class:'form-control' }}
            </div>
            <div class="form-group">شماره تماس شرکت
                {{ form.organization_phone|add_class:'form-control' }}
            </div>
            <div class="form-group">تعداد کارکنان
                {{ form.employees_number|add_class:'form-control' }}
            </div>
            <div class="form-group">ایمیل
                {{ form.email|add_class:'form-control' }}
            </div>
            <div class="form-group">نام و نام خانوادگی مخاطب
                {{ form.owner|add_class:'form-control' }}
            </div>
            <div class="form-group">شماره تماس مخاطب
                {{ form.owner_phone|add_class:'form-control' }}
            </div>
            <div class="form-group">محصولات تولیدی شرکت
                {{ form.organization_product }}<a href="{% url 'organ_product' %}" style="background-color: yellow">➕</a>
            </div>

            <input type="submit" value="Confirm" href="{% url 'organ_list' %}">

        </form>
    </div>

{% endblock %}

CRMsoftware/organs/templates/organs/base.html
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>

<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}My products{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">

    <style>
        .modal-header, h4, .close {
            background-color: #5cb85c;
            color: white !important;
            text-align: center;
            font-size: 30px;
        }

        .modal-footer {
            background-color: #f9f9f9;
        }
    </style>
</head>

<body style="background-color: #2b542c">

<div id="header">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #5993bb">
        <span class="navbar-brand mb-0 h1 ml-5">CRM</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'products:product_list' %}">محصولات<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'organ_list' %}">سازمان</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'quotes:quote_list' %}">فاکتور</a>
                </li>
            </div>
            <div class="navbar-nav mr-auto">
                <li class="navbar-nav">
                    {% if not user.is_authenticated %}
                        <a class="navbar-brand" href={% url 'users:login' %}>ورود<i
                                class="fa fa-sign-in-alt ml-1 mr-1"></i></a>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <a class="navbar-brand">{{ user.username }}</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <a class="navbar-brand" style="color: #c80000" href="{% url 'users:logout' %}">خروج</a>
                    {% endif %}

                </li>
            </div>

        </div>
    </nav>
</div>


<div class="container">
    <div class="col-12">
        {% if messages %}
            {% for message in messages %}

                <div class="alert alert-success">
                    {{ message }}
                    <button type="button" data-dismiss="alert" class="close">&times;</button>
                </div>

            {% endfor %}
        {% endif %}
    </div>
</div>

<div id="content">
    {% block content %}
    {% endblock %}
</div>

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
{% block page_scripts %}{% endblock %}
</html>

CRMsoftware/organs/templates/organs/base1.html
{% load i18n %}
{% load static %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<html {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <title>
        PhoneBook:
        {% block page_header_title %}
            {{ page_title }}
        {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/util.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/all.css' %}" rel="stylesheet">
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-info">
    {% if user.is_authenticated %}
        <a class="navbar-brand" }>{% trans 'ایجاد مخاطب' %}</a>

        <a class="navbar-brand" >{% trans 'Search' %}</a>

        <a class="navbar-brand" >{%trans 'مخاطبین' %}</a>

        <a class="navbar-brand">{% trans 'فعالیت ها' %}</a>
    {% endif %}
    <ul class="navbar-nav ml-auto">
        {% if not user.is_authenticated %}
            <a class="navbar-brand" > {% trans 'ورود' %}<i class="fa fa-sign-in-alt ml-1 mr-1"></i></a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="navbar-brand" style="color: #c80000" >{% trans 'خروج' %}</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="navbar-brand" >{{ user.username }}</a>
        {% endif %}
    </ul>
</nav>

{# Django`s messages #}
<div class="container">
    <div class="col-12">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-info">
                    {{ message }}
                    <button type="button" data-dismiss="alert" class="close">&times;</button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

{% block content %}YOUR CONTENT GOES HEAR{% endblock %}

<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>

{% block page_scripts %}{% endblock %}
<footer class="text-muted">
    <div class="container">
        <span class="text-muted align-content-center">Copyright &copy; {{ year }}</span>
        <p class="float-right">
            <a href="#" style="color: #005cbf">Back to top ⬆</a>
        </p>
    </div>
</footer>

</body>
</html>

CRMsoftware/organs/templates/organs/followup_detail.html
{% extends 'organs/base.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Organs{% endif %}
{% endblock %}
{% block content %}


    <form method="get">
        <div class="container">
            <div class="jumbotron">
                <h1>تاریخچه ی پیگیری های سازمان {{ object }}</h1>
            <button><a href="{% url 'organ_list' %}">بازگشت</a></button>


            </div>


        <div class="container">
        <div class="col-sm">

            <table class="table table-striped" style="background-color: white">
                <thead>
                <tr>
                    <th scope="col" class="col-lg-1">#</th>

                    <th scope="col" class="col-lg-2">ثبت توسط</th>
                    <th scope="col" class="col-lg-3">تاریخ ثبت</th>
                    <th scope="col" class="col-lg-5">توضیحات</th>

                </tr>
                </thead>
                <tbody>
                {% for obj in description.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>

                        <td>{{ obj.created_by }}</td>
                        <td>{{ obj.created|date:"Y-m-d , H:i:s" }}</td>
                        <td>{{ obj.description }}</td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
            </div>
            </div>
    </form>
{% endblock %}

CRMsoftware/organs/templates/organs/followup_form.html
{% extends 'organs/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <div class="form-group col-lg-6">
        <form class="form-group" method="post">
            {% csrf_token %}

            <label for="description"></label>
            <textarea class="form-control" rows="5" id="description" name="description"
                      placeholder="توضیحات را اینجا وارد نمایید"></textarea>

        </form>
        <br>

        <button class="btn btn-primary" type="submit" id="save">ذخیره</button>
    </div>
{% endblock %}
{% block page_scripts %}
    <script>
        $(document).ready(function () {
            $('#save').on('click', function (event) {
                var description = $('#description').val();

                $.ajax({
                    method: 'POST',
                    url: '{% url 'organ-description' organ_obj.pk %}',
                    data: {
                        description: description
                    },
                    success: function (response) {
                        alert('با موفقیت ذخیره شد.');
                    },
                    error: function (response) {
                        alert('اطلاعات وارد شده صحیح نیست.');
                    },

                })
            });
        });
    </script>

{% endblock %}

CRMsoftware/organs/templates/organs/organization_detail.html
{% extends 'organs/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Detail
{% endblock %}
{% block content %}
<div id="sidebar"><header style="color: white">مشخصات مخاطب</header>
    <table class="table table-striped" style="background-color: white">
        <thead>
                <tr>
                    <th scope="row">نام و نام خانوادگی</th>
                    <th scope="row">شماره تماس</th>
                </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">{{ object.owner }}</th>
            <th scope="row">{{ object.owner_phone }}</th>
        </tr>
        </tbody>
    </table>
</div>
    <form method="get">
        <div class="container">
            <div class="jumbotron">
                <h1> مشخصات سازمان:{{ object.name }}</h1>
                <button>
                    <a href="{% url 'organ_list' %}">بازگشت</a>
                </button>
                <button><a  href="{% url 'quotes:new_quote' %}">صدور پیش فاکتور</a></button>
                <button>
                    <a href="{% url 'organ_edit' object.pk %}">ویرایش</a>
                </button>

            </div>


        <div class="container">
        <div class="col-sm">

            <table class="table table-striped" style="background-color: white">
                <thead>
                <tr>
                    <th scope="col">استان</th>
                    <th scope="col">تلفن</th>
                    <th scope="col">تعداد کارکنان</th>
                    <th scope="col">محصولات تولیدی</th>
                    <th scope="col">محصولات پیشنهادی ما</th>
                    <th scope="col">ثبت توسط</th>
                    <th scope="col">تاریخ ثبت</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ object.province }}</td>
                    <td>{{ object.organization_phone }}</td>
                    <td>{{ object.employees_number }}</td>
                    <td>{% for product in object.organization_product.all %}{{ product.name }}<br>{% endfor %}</td>
                    <td>{% for related_product in offer_product %}{{ related_product.name }}<br> {% endfor %}</td>
                    <td>{{ object.created_by }}</td>
                    <td>{{ object.created_at|date:"Y-m-d" }}</td>
                </tr>
                </tbody>
            </table>

        </div>
            </div>
            </div>
    </form>

{% endblock %}

CRMsoftware/organs/templates/organs/organization_form.html
{% extends 'organs/base.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Edit{% endif %}
{% endblock %}
{% block content %}

    <form method="post">
        <div class="container">
            <div class="jumbotron">
                <h1>ویرایش مشخصات سازمان:{{ object.name }}</h1>
                <button><a href="{% url 'organ_list' %}"></a>بازگشت</button>

            </div>
            <div style="color: white">
                {{ form.as_p }}
            </div>
        </div>

        <input type="submit" value="Confirm" href="{% url 'organ_list' %}">
    </form>
{% endblock %}

CRMsoftware/organs/templates/organs/organization_list.html
{% extends 'organs/base.html' %}
{% load static %}

{% block title %}
    Organs
{% endblock %}
{% block content %}
    <div class="container-fluid col-lg-10">
        <div class="button btn-sm">
            <button class="header btn-block"><a style="color: black" href="{% url 'create_organ' %}">ایجاد شرکت جدید</a>
            </button>
        </div>
        <form method="get">

            <div class="product-list">
                <table class="table table-striped" style="background-color: white">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">نام سازمان</th>
                        <th scope="col">استان</th>
                        <th scope="col">نام مخاطب</th>
                        <th scope="col">تلفن</th>
                        <th scope="col">ثبت توسط</th>
                        <th scope="col">تاریخ ثبت</th>
                        <th scope="col">عملیات</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for organ in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a href="{% url 'organ_detail' organ.pk %}" id="data">{{ organ.name }}</a></td>
                            <td>{{ organ.province }}</td>
                            <td>{{ organ.owner }}</td>
                            <td>{{ organ.organization_phone }}</td>
                            <td>{{ organ.created_by }}</td>
                            <td>{{ organ.created_at|date:"Y-m-d , H:i:s" }}</td>


                            <td>
                                <a href="{% url 'organ-description' organ.pk %}"> ثبت پیگیری</a>
                                <a href="{% url 'followup-detail' organ.pk %}">🧐</a>

                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </form>

        {% include 'organs/pagination.html' %}

    </div>

{% endblock %}

CRMsoftware/organs/templates/organs/product_entry.html
{% extends 'organs/base.html' %}
{% load static %}
{#{% load widget_tweaks %}#}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% block content %}

    <h1 class="mt-5 mb-4"><i class="fa fa-phone-volume ml-2"></i>New product</h1>
    <form method="post">{% csrf_token %}

            {{ form.as_p}}
            <input type="submit" value="Confirm">

    </form>


{% endblock %}